# Generated by Django 4.2.2 on 2023-09-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("librarydb", "0007_book_loan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="givenname",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Given names"
            ),
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arrangers",
                    models.ManyToManyField(
                        blank=True, related_name="arranged_music", to="librarydb.author"
                    ),
                ),
                (
                    "book_or_folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="librarydb.book"
                    ),
                ),
                (
                    "composers",
                    models.ManyToManyField(
                        blank=True, related_name="composed_music", to="librarydb.author"
                    ),
                ),
            ],
        ),
    ]
