# Generated by Django 4.2.2 on 2023-09-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("librarydb", "0008_alter_author_givenname_music"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="music",
            options={"ordering": ("title",), "verbose_name_plural": "Music"},
        ),
        migrations.AddField(
            model_name="music",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
