# Generated by Django 4.1.3 on 2022-12-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarydb", "0002_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(blank=True, to="librarydb.author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="ISBN"
            ),
        ),
    ]
