# Generated by Django 4.1.3 on 2023-02-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("librarydb", "0006_book_loaned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="loan_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
